package util;

public enum View {
	HOME,
	MEMBER_LOGIN, MEMBER_HOME,
	MEMBER_JOIN, MEMBER_DELETE,
	ADMIN_LOGIN, ADMIN_HOME,
	
	CLASS_LIST, // 수업 리스트
	CLASS_SEARCH, CLASS_SELECT,
	CLASS_INSERT, CLASS_UPDATE,
	RGSTR_CLASS,
	RGSTR_LIST, // 수강신청 리스트
	RGSTR_DETAIL, // 수강신청 상세조회
	RGSTR_DELETE, // 수강신청 삭제
	PASS_MGMT, // 수강권 정보
	EXPIRED_PASS, // 지난 수강권 정보
	PASS_PURCHASE,
	
	REVIEW_HOME, REVIEW_LIST, REVIEW_SEARCH,
	REVIEW_DETAIL, 
	REVIEW_INSERT, REVIEW_DELETE,
	
	NOTICE_LIST, //일반회원 용
	NOTICE_HOME, //어드민 용 
	NOTICE_DETAIL,
	NOTICE_INSERT, NOTICE_UPDATE, NOTICE_DELETE, RGSTR_CLASS_LIST, 
	
	
	ADMIN_RGSTR, CLASS_MGMT, ADMIN_REVIEWDT, ADMIN_REVIEW, 
	ADMIN_REVIEW_DELETE, ADMIN_NOTICE, ADMIN_NOTICEDT
	
}
